# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ISO19157
                                 A QGIS plugin
 Aplicación de la norma ISO 19157 sobre la BTN25 del CNIG
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-02-18
        copyright            : (C) 2021 by Harold Mercado LLanos
        email                : hmercado78@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ISO19157 class from file ISO19157.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .iso_19157 import ISO19157
    return ISO19157(iface)
